//! IEEE MA-L OUI vendor lookup.
//!
//! The full registry (~39k prefixes) is embedded as a compact `PREFIX\tVendor`
//! table generated by `scripts/generate_oui.py`. It is parsed into a HashMap
//! exactly once on first use via `OnceLock`, giving O(1) vendor lookups.

use std::collections::HashMap;
use std::sync::OnceLock;

const OUI_DATA: &str = include_str!("oui_data.tsv");

static MAP: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();

fn map() -> &'static HashMap<&'static str, &'static str> {
    MAP.get_or_init(|| {
        let mut m = HashMap::with_capacity(40_000);
        for line in OUI_DATA.lines() {
            if let Some((prefix, vendor)) = line.split_once('\t') {
                m.insert(prefix, vendor);
            }
        }
        m
    })
}

/// Look up the vendor for a MAC address. Accepts any common separator style.
/// Returns `None` if the prefix is unknown or the MAC is malformed.
pub fn lookup(mac: &str) -> Option<String> {
    let hex: String = mac
        .chars()
        .filter(|c| c.is_ascii_hexdigit())
        .take(6)
        .collect::<String>()
        .to_ascii_uppercase();
    if hex.len() != 6 {
        return None;
    }
    map().get(hex.as_str()).map(|v| v.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_prefix_resolves() {
        // 00:00:00 is Xerox in the registry.
        assert!(lookup("00:00:00:11:22:33").is_some());
    }

    #[test]
    fn malformed_returns_none() {
        assert_eq!(lookup("zz"), None);
    }
}
