//! Which edition of ArcScan this binary is, and where this process keeps state.
//!
//! The edition is an explicit Cargo feature. Installed ArcScan keeps using its
//! normal application-data directory. Portable ArcScan gets one fresh session
//! below the operating system's temporary directory; neither executable name,
//! current directory nor anything beside the executable can change that choice.

use std::fmt;
use std::path::{Path, PathBuf};

use serde::Serialize;

pub const PORTABLE_NAMESPACE_DIR: &str = "ArcScanPortable";
pub const PORTABLE_SESSIONS_DIR: &str = "sessions";
pub const DATABASE_FILE: &str = "arcscan.db";
pub const WEBVIEW_DIR: &str = "WebView";
pub const OWNERSHIP_MARKER_FILE: &str = ".arcscan-portable-session";
pub const ACTIVE_LOCK_FILE: &str = ".arcscan-portable-session.lock";
pub const NAMESPACE_LOCK_FILE: &str = ".sessions.lock";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Edition {
    Installed,
    Portable,
}

impl Edition {
    pub const fn current() -> Self {
        if cfg!(feature = "portable") {
            Edition::Portable
        } else {
            Edition::Installed
        }
    }

    pub const fn is_portable(self) -> bool {
        matches!(self, Edition::Portable)
    }
}

impl fmt::Display for Edition {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Edition::Installed => "installed",
            Edition::Portable => "portable",
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum UpdaterMode {
    Installer,
    Manual,
}

impl UpdaterMode {
    #[cfg(test)]
    pub const fn current() -> Self {
        match Edition::current() {
            Edition::Installed => UpdaterMode::Installer,
            Edition::Portable => UpdaterMode::Manual,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum StorageMode {
    Persistent,
    Temporary,
}

pub const fn platform() -> &'static str {
    if cfg!(target_os = "windows") {
        "Windows"
    } else if cfg!(target_os = "macos") {
        "macOS"
    } else if cfg!(target_os = "linux") {
        "Linux"
    } else {
        "Desktop"
    }
}

pub const fn architecture() -> &'static str {
    if cfg!(target_arch = "x86_64") {
        "x64"
    } else if cfg!(target_arch = "aarch64") {
        "ARM64"
    } else if cfg!(target_arch = "x86") {
        "x86"
    } else {
        "unknown"
    }
}

/// All paths owned by one Portable process.
///
/// `session_id` is generated by the backend. It is never accepted from the UI,
/// a command line, the executable folder or the ownership marker.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PortableLayout {
    pub namespace_root: PathBuf,
    pub sessions_root: PathBuf,
    pub session_id: String,
    pub session_root: PathBuf,
    pub database_path: PathBuf,
    pub webview_data_path: PathBuf,
    pub ownership_marker_path: PathBuf,
    pub active_lock_path: PathBuf,
    pub namespace_lock_path: PathBuf,
}

impl PortableLayout {
    pub fn for_session(system_temp: &Path, session_id: &str) -> Self {
        let namespace_root = system_temp.join(PORTABLE_NAMESPACE_DIR);
        let sessions_root = namespace_root.join(PORTABLE_SESSIONS_DIR);
        Self::from_sessions_root(sessions_root, session_id)
    }

    pub(crate) fn from_sessions_root(sessions_root: PathBuf, session_id: &str) -> Self {
        let namespace_root = sessions_root
            .parent()
            .expect("sessions root always has its ArcScan namespace parent")
            .to_path_buf();
        let session_root = sessions_root.join(session_id);
        PortableLayout {
            database_path: session_root.join(DATABASE_FILE),
            webview_data_path: session_root.join(WEBVIEW_DIR),
            ownership_marker_path: session_root.join(OWNERSHIP_MARKER_FILE),
            active_lock_path: session_root.join(ACTIVE_LOCK_FILE),
            namespace_lock_path: namespace_root.join(NAMESPACE_LOCK_FILE),
            namespace_root,
            sessions_root,
            session_id: session_id.to_string(),
            session_root,
        }
    }
}

/// Session identifiers are UUID v4 values in compact lower-case form.
///
/// Keeping this grammar narrow makes it possible to prove that a cleanup target
/// is one direct child of `sessions/` before any recursive operation begins.
pub(crate) fn valid_session_id(value: &str) -> bool {
    value.len() == 32
        && value
            .bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
        && value.as_bytes()[12] == b'4'
        && matches!(value.as_bytes()[16], b'8' | b'9' | b'a' | b'b')
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct RuntimeInfo {
    pub edition: Edition,
    pub version: String,
    pub platform: &'static str,
    pub architecture: &'static str,
    pub storage_mode: StorageMode,
    /// Installed data remains diagnosable. Portable session paths stay in Rust;
    /// exposing a disposable internal path would encourage saving into it.
    pub data_root: Option<String>,
    pub updater_mode: UpdaterMode,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuntimePaths {
    pub edition: Edition,
    pub data_root: PathBuf,
    pub database_path: PathBuf,
    /// `Some` only in Portable mode and always below the unique session root.
    pub webview_data_path: Option<PathBuf>,
}

impl RuntimePaths {
    pub fn installed(app_data_dir: PathBuf) -> Self {
        RuntimePaths {
            edition: Edition::Installed,
            database_path: app_data_dir.join(DATABASE_FILE),
            data_root: app_data_dir,
            webview_data_path: None,
        }
    }

    pub fn portable(layout: &PortableLayout) -> Self {
        RuntimePaths {
            edition: Edition::Portable,
            data_root: layout.session_root.clone(),
            database_path: layout.database_path.clone(),
            webview_data_path: Some(layout.webview_data_path.clone()),
        }
    }

    pub fn info(&self) -> RuntimeInfo {
        let portable = self.edition.is_portable();
        RuntimeInfo {
            edition: self.edition,
            version: env!("CARGO_PKG_VERSION").to_string(),
            platform: platform(),
            architecture: architecture(),
            storage_mode: if portable {
                StorageMode::Temporary
            } else {
                StorageMode::Persistent
            },
            data_root: (!portable).then(|| self.data_root.display().to_string()),
            updater_mode: if portable {
                UpdaterMode::Manual
            } else {
                UpdaterMode::Installer
            },
        }
    }

    /// Whether an export destination is inside this disposable session.
    ///
    /// The target file usually does not exist yet, so its existing parent is
    /// canonicalized. A conservative lexical check runs first and also rejects
    /// paths containing `..` that begin inside the session.
    pub fn export_is_inside_temporary_session(&self, path: &Path) -> bool {
        if !self.edition.is_portable() {
            return false;
        }
        if path.starts_with(&self.data_root) {
            return true;
        }

        let root = std::fs::canonicalize(&self.data_root).ok();
        let parent = path.parent().and_then(|p| std::fs::canonicalize(p).ok());
        match (root, parent) {
            (Some(root), Some(parent)) => parent.starts_with(&root),
            _ => false,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PortableError {
    TemporarySessionUnavailable { path: String, detail: String },
    DatabaseUnavailable { path: String, detail: String },
}

impl PortableError {
    pub fn message(&self) -> String {
        "ArcScan Portable could not create a temporary session.\n\nCheck that Windows temporary \
         storage is available and writable, then try again."
            .into()
    }

    pub fn detail(&self) -> Option<String> {
        match self {
            PortableError::TemporarySessionUnavailable { path, detail } => {
                Some(format!("Temporary session path {path}: {detail}"))
            }
            PortableError::DatabaseUnavailable { path, detail } => Some(format!(
                "Could not open temporary database {path}: {detail}"
            )),
        }
    }
}

impl fmt::Display for PortableError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.detail() {
            Some(detail) => write!(f, "{} ({detail})", self.message().replace('\n', " ")),
            None => f.write_str(&self.message().replace('\n', " ")),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_edition_and_updater_are_compiled_in() {
        let edition = Edition::current();
        assert_eq!(edition.is_portable(), cfg!(feature = "portable"));
        assert_eq!(
            UpdaterMode::current(),
            if edition.is_portable() {
                UpdaterMode::Manual
            } else {
                UpdaterMode::Installer
            }
        );
    }

    #[test]
    fn wire_values_are_stable() {
        assert_eq!(
            serde_json::to_string(&Edition::Portable).unwrap(),
            "\"portable\""
        );
        assert_eq!(
            serde_json::to_string(&Edition::Installed).unwrap(),
            "\"installed\""
        );
        assert_eq!(
            serde_json::to_string(&UpdaterMode::Manual).unwrap(),
            "\"manual\""
        );
        assert_eq!(
            serde_json::to_string(&StorageMode::Temporary).unwrap(),
            "\"temporary\""
        );
    }

    #[test]
    fn the_platform_and_architecture_come_from_the_build() {
        assert!(["Windows", "macOS", "Linux", "Desktop"].contains(&platform()));
        assert!(["x64", "ARM64", "x86", "unknown"].contains(&architecture()));
    }

    #[test]
    fn a_portable_layout_is_inside_the_exact_temp_namespace() {
        let id = "0123456789ab4def8123456789abcdef";
        let layout = PortableLayout::for_session(Path::new("/system/temp"), id);
        assert_eq!(
            layout.session_root,
            Path::new("/system/temp/ArcScanPortable/sessions").join(id)
        );
        assert_eq!(layout.database_path, layout.session_root.join("arcscan.db"));
        assert_eq!(
            layout.webview_data_path,
            layout.session_root.join("WebView")
        );
        assert_eq!(
            layout.ownership_marker_path,
            layout.session_root.join(".arcscan-portable-session")
        );
        assert_eq!(
            layout.active_lock_path,
            layout.session_root.join(".arcscan-portable-session.lock")
        );
    }

    #[test]
    fn session_id_grammar_is_narrow() {
        assert!(valid_session_id("0123456789ab4def8123456789abcdef"));
        for invalid in [
            "",
            "0123456789abcdef",
            "0123456789ABCDEF0123456789ABCDEF",
            "0123456789abcdef0123456789abcdef",
            "0123456789ab4def7123456789abcdef",
            "../../outside",
            "0123456789abcdef0123456789abcdeg",
            "01234567-89ab-cdef-0123-456789abcdef",
        ] {
            assert!(!valid_session_id(invalid), "accepted {invalid}");
        }
    }

    #[test]
    fn executable_folder_is_not_part_of_the_portable_layout() {
        let id = "0123456789ab4def8123456789abcdef";
        let layout = PortableLayout::for_session(Path::new("/system/temp"), id);
        assert!(!layout.session_root.starts_with("/opt/ArcScan"));
        assert!(!layout.session_root.starts_with("D:/field-kit/ArcScan"));
    }

    #[test]
    fn two_session_ids_share_nothing() {
        let a = PortableLayout::for_session(
            Path::new("/system/temp"),
            "0123456789ab4def8123456789abcdef",
        );
        let b = PortableLayout::for_session(
            Path::new("/system/temp"),
            "fedcba9876544abc8fedcba987654321",
        );
        assert_ne!(a.session_root, b.session_root);
        assert_ne!(a.database_path, b.database_path);
        assert_ne!(a.webview_data_path, b.webview_data_path);
        assert!(!a.session_root.starts_with(&b.session_root));
        assert!(!b.session_root.starts_with(&a.session_root));
    }

    #[test]
    fn installed_paths_are_unchanged() {
        let paths = RuntimePaths::installed(PathBuf::from("/app/data/com.arcscan.app"));
        assert_eq!(paths.edition, Edition::Installed);
        assert_eq!(
            paths.database_path,
            Path::new("/app/data/com.arcscan.app/arcscan.db")
        );
        assert_eq!(paths.webview_data_path, None);
        assert_eq!(paths.info().storage_mode, StorageMode::Persistent);
        assert_eq!(
            paths.info().data_root.as_deref(),
            Some("/app/data/com.arcscan.app")
        );
    }

    #[test]
    fn portable_runtime_info_calls_storage_temporary_and_hides_the_path() {
        let layout = PortableLayout::for_session(
            Path::new("/system/temp"),
            "0123456789ab4def8123456789abcdef",
        );
        let paths = RuntimePaths::portable(&layout);
        let info = paths.info();
        let json = serde_json::to_string(&info).unwrap();
        assert_eq!(info.storage_mode, StorageMode::Temporary);
        assert_eq!(info.data_root, None);
        assert!(!json.contains("ArcScanPortable"));
        assert!(!json.contains("arcscan.db"));
        assert!(!json.contains("WebView"));
    }

    #[test]
    fn installed_and_portable_sqlite_and_profiles_do_not_overlap() {
        let installed = RuntimePaths::installed(PathBuf::from("/app/data/com.arcscan.app"));
        let layout = PortableLayout::for_session(
            Path::new("/system/temp"),
            "0123456789ab4def8123456789abcdef",
        );
        let portable = RuntimePaths::portable(&layout);
        assert_ne!(installed.database_path, portable.database_path);
        assert!(!portable.database_path.starts_with(&installed.data_root));
        assert!(!installed.database_path.starts_with(&portable.data_root));
        assert_eq!(portable.webview_data_path, Some(layout.webview_data_path));
    }

    #[test]
    fn only_portable_rejects_an_export_inside_its_session() {
        let layout = PortableLayout::for_session(
            Path::new("/system/temp"),
            "0123456789ab4def8123456789abcdef",
        );
        let portable = RuntimePaths::portable(&layout);
        let installed = RuntimePaths::installed(PathBuf::from("/app/data/com.arcscan.app"));
        let inside = layout.session_root.join("export.csv");
        let outside = Path::new("/operator/exports/export.csv");
        assert!(portable.export_is_inside_temporary_session(&inside));
        assert!(!portable.export_is_inside_temporary_session(outside));
        assert!(!installed.export_is_inside_temporary_session(&inside));
    }

    #[test]
    fn startup_errors_name_temp_storage_and_never_offer_appdata() {
        let error = PortableError::TemporarySessionUnavailable {
            path: "C:\\Temp\\ArcScanPortable".into(),
            detail: "access denied".into(),
        };
        let lower = error.message().to_lowercase();
        assert!(lower.contains("temporary session"));
        assert!(lower.contains("temporary storage"));
        assert!(!lower.contains("appdata"));
        assert!(!lower.contains("application data"));
        assert!(!lower.contains("fall back"));
    }
}
